### ISSUE TITLE
Scaling this

### ISSUE THREAD

**Issue by dabreegster** [actenglabs/abstreet-to-atip#1]
This repo now has a tool for exporting area polygons in geojson from the LTN tool. It works off one pre-built A/B Street map at a time. So, to make the polygons available for import to ATIP, a few things are needed.

## A/B Street maps for all of the UK

Aka, solve https://github.com/a-b-street/abstreet/issues/1009

## Output files

The output will just be polygons covering the whole UK. It's trivial to union files from different areas. We could stick the results in a flatgeobuf or any kind of vector tile.

## Storage

In the very short term, we can host these with Github releases, or I can stick them on S3 somewhere.

**Comment by dabreegster** [comment]
Small part of Bristol geojson is about 900KB, 150KB gzipped. The area polygons are super detailed, snapped perfectly to osm2street's understanding of the road edges. Obviously we don't need that level of quality for ATIP; we could also just aggressively downsample to squeeze down size

**Comment by Robinlovelace** [comment]
Great you're thinking about this already.

**Comment by dabreegster** [comment]
# Notes on trying to import a bunch of tiled regions into abst

Need to exclude Wales and Scotland from the boundary

- `generate_tiles.py` to create boundaries
- `./target/x86_64-unknown-linux-gnu/release/cli geojson-to-osmosis ~/uk_tiles.geojson`  about 3000, oh boy...
- grab http://download.geofabrik.de/europe/great-britain/england-latest.osm.pbf, about 1GB. manually stash in `data/input/gb/tiled/osm/`
- put all the boundaries in `importer/config/gb/tiled` ... will want to name these better for sure

**Comment by dabreegster** [comment]
Hack `importer/src/utils.rs` `pick_geofabrik` routine to use the one giant osm.pbf and also implicitlyish skip Wales & Scotland

**Comment by dabreegster** [comment]
`osmconvert` absolutely dominates time. For a tiny tile, about 1s to convert and 100s to turn the osm.pbf into the osm.xml

**Comment by dabreegster** [comment]
`time osmconvert czech-republic-latest.osm.pbf -B=/home/dabreegster/abstreet/importer/config/cz/frydek_mistek/huge.poly --complete-ways -o=osmconvert.osm` takes about 27s

`time osmium extract czech-republic-latest.osm.pbf -p /home/dabreegster/abstreet/importer/config/cz/frydek_mistek/huge.poly -o osmium.osm` takes about 13s

`osmium` can understand Osmosis polygon files, but also just normal geojson. It can also make multiple extracts in one pass, but I need to test the perf and memory requirements of this. Some short-term fixes to the A/B Street process to scale better:

- switch to osmium (converting all osmosis polygons into geojson, and removing lots of code) (don't forget to update docs)
- use `-f osm,add_metadata=false` to strip out version, timestamp, author tags. We don't use them, and it should be bit faster to store and work with smaller files
- Let's remove the `.osm` XML files from S3 and the updater. They're trivial to produce from the osm.pbf (which we should still store for reproducibility). Can keep them locally, but can save on my bandwidth a bit by not uploading them all the time. Currently they're taking about 9GB

**Comment by dabreegster** [comment]
`time osmium extract -v -c uk_tiles_1.json /home/dabreegster/abstreet/data/input/gb/tiled/osm/england-latest.osm.pbf`
The first set nearly ate my 12GB of RAM. 50 .osm extracts are just 64MB, because the first tiles are way up north, in the land of sparseness

**Comment by dabreegster** [comment]
![Screenshot from 2022-10-26 15-03-18](https://user-images.githubusercontent.com/1664407/198047366-c3630763-dc44-459a-b8dd-182a95d99fae.png)
https://github.com/acteng/abstreet-to-atip/blob/main/split_uk_osm.sh

OK, now we're getting somewhere. For the moment I'm ditching tiles, just using the huge authority boundaries instead. (But the workflow will take any kind of geojson input.) Can produce osm.xml files now, mostly just disk/memory bound.

Now I'm going to import these OSM extracts and... since the most important thing seems to be the route-snapper, see how small we could get the file just needed for that. We don't even need full osm2streets representation.

**Comment by dabreegster** [comment]
The full A/B Street import process for some of these extracts is quite revealing. Depending what we need as final output, we can really cut out time. In Gloucestershire, the full import took 103s. Only 10 to initially make the street network (which is all we'd need for the route snapper). The "collapse degenerate intersections" transform is a bottleneck at 30s, likely very easy to fix.

**Comment by dabreegster** [comment]
Aaaand reading the osm.xml to a string (done for better WASMness) thing is dumb and breaking for Greater London, need to fix that

**Comment by dabreegster** [comment]
OK, few different related efforts, but need to detangle. All of them kind of desired by Tuesday!

- get all of the UK to work in the LTN tool specifically
  - we could import the massive authority areas, but using the result on the web would be so so painful
  - would need to do the `enum Source` thing and parse XML from a file sometimes, for big areas
  - ---> or... just import all of the tiles, decide where to store them and how to index/access them  <---
- get the route snapper working everywhere
  - let's see how big the file would be JUST for the needed state here, if we use entire authority areas. because that would be simplest.
  - if not, we could also try tiling
- get LTN areas importable to ATIP everywhere
  - tiling won't really work here; entire authority areas would probably be easiest

**Comment by dabreegster** [comment]
For Gloucestershire, just the `StreetNetwork` bincoded is 50MB. Gzipped is 10MB.
"Just crazy enough to work."

I'll try stripping out even more state though, for route snapping

**Comment by dabreegster** [comment]
Alright here we go, Gloucestershire is 6MB or 5MB gzipped with just the road geometry. It'll be a little bit more with graph structure added, but not by much. (And the road points could be smoothed / simplified to compress even more; we don't need super precise curve following)

**Comment by Robinlovelace** [comment]
5MB sounds eminently workable, look forward to testing!

**Comment by dabreegster** [comment]
https://user-images.githubusercontent.com/1664407/198291950-be724657-8761-4908-91d3-3669488c26f0.mp4

We are in business...

**Comment by Robinlovelace** [comment]
So snappy! So that same process could work for any LAD? LAD boundaries: https://github.com/udsleeds/openinfra/blob/main/data-small/Local_Authority_Districts_(May_2022)_UK_BSC.geojson

**Comment by dabreegster** [comment]
`for x in ~/abstreet-to-atip/uk_osm/out/*; do echo ./target/release/cli oneshot-import --drive-on-left $x --clip-path ~/abstreet-to-atip/uk_osm/$(basename $x .osm).geojson; done`

**Comment by dabreegster** [comment]
Nothing actionable or relevant in this issue. https://github.com/a-b-street/abstreet/issues/1009 has more up-to-date notes on importing lots of places into A/B Street, and about to clean that up further for use in ATIP
