### ISSUE TITLE
Multipolygon authority areas are problematic

### ISSUE THREAD

**Issue by dabreegster** [actenglabs/abstreet-to-atip#4]
@Robinlovelace, the reason https://acteng.github.io/atip/scheme.html?authority=Cornwall and other places break for the route snapper is that they use a multipolygon. Currently we're taking only the first polygon in the list as the boundary area, and for Cornwall, this happens to contain no roads. I'm going to workaround, but supporting multipolygon boundaries all the way downstream in osm2streets is a hassle, and I'm not sure a correct decision. Is there an easy way on your end to produce one envelope around such authorities -- maybe using concave hull or something?

**Comment by Robinlovelace** [comment]
Concave Hull should do it yes: https://gis.stackexchange.com/questions/439271/simplify-multipolygon-removing-small-gaps-in-postgis

**Comment by Robinlovelace** [comment]
Would love to use the Rust implementation but that would take too long and be another distraction! https://docs.rs/geo/0.17.1/geo/algorithm/concave_hull/trait.ConcaveHull.html

**Comment by Robinlovelace** [comment]
Progress, tho it may not look like it... 
![image](https://user-images.githubusercontent.com/1825120/203177500-976e661c-2e29-4461-8876-a5df5ae2915b.png)

**Comment by Robinlovelace** [comment]
Simpler approach: buffer the small bits.

![image](https://user-images.githubusercontent.com/1825120/203179156-bac954e6-a2c1-4dd1-822b-bc6c59efd32b.png)

**Comment by dabreegster** [comment]
A user reports a problem in Portsmouth: https://atip.uk/scheme.html?authority=Portsmouth#12.47/50.83244/-1.06048
The largest area is the south bit, so the route snapper doesn't work on the mainland at all:

https://user-images.githubusercontent.com/1664407/216995553-552328ca-6e49-432a-9e5a-4dbfc83d69e5.mp4

A single polygon, maybe using convex or concave hull, would be preferable in this case. I'll think about other workarounds.

**Comment by dabreegster** [comment]
So far, convex hull has been working fine, so closing
